// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbszfcszxjcnetfgjsra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtic3pmY3N6eGpjbmV0Zmdqc3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjY2NjMsImV4cCI6MjA2NzgwMjY2M30.FdnmQa-kaTdQn3ThKx1mZLV4NKXJbzbiire7qDP6rkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});